### ISSUE TITLE
Endpoint to get assets

### ISSUE THREAD

**Issue by sbres** [coinflex-exchange/API#1]
Is it possible to have an endpoint where we can retrieve the assets available on the exchange?

**Comment by jamescoinflex** [comment]
This should be coming soon, but currently isn’t available. The assets list can be found in SCALE.md and the active futures contracts can be found in the CONTRACTS.md page by examining the start and expiry columns. Thanks

**Comment by fl4p-old** [comment]
Shouldn't this stay open for visibility?
